---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"

  tasks:
#################### Build go-dappley ####################
  - name: Make build
    make:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
      target: build
      file: /home/ubuntu/go/src/github.com/dappley/go-dappley/Makefile


#################### Generate new node configuration file ####################
  - name: Generate new node configuration file
    ansible.builtin.expect:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
      command: ./cli generateConfig
      responses:
        Question:
          - 'MinerNode'
          - 'node6'
          - ''
          - 'dappley'
          - ''
          - 'CAISICMUvaL/UxDELHpZiTbJ7subEtRverOR7XFndu4y/CUO'
          - ''
          - '50056'
          - ''
    register: new_node_config
    when: inventory_hostname in groups['NODE1']
        # 'Please input the password for the new account:' : 'dappley'
        # 'Repeat password:' : 'dappley'

  - debug:
      msg: '{{ new_node_config }}'
    when: inventory_hostname in groups['NODE1']

  - name: Move node6.conf to Jenkins
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node6.conf
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node6/
      flat: yes
    when: inventory_hostname in groups['NODE1']

  - name: Copy accounts.dat to all hosts
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node6/node6.conf
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf
    when: inventory_hostname in groups['NODE2'] or inventory_hostname in groups['NODE3'] inventory_hostname in groups['NODE4'] inventory_hostname in groups['NODE5'] inventory_hostname in groups['NODE6']

# Choose config type:
# FullNode or MinerNode:

# Ans - MinerNode
# Ans - FullNode

# File name(don't need extension name): Input nothing for default: "node"

# Ans - node6

# Miner address info:
# Input nothing to generate new key pair or input valueable key pair
# miner_address:

# Ans - Nothing
# Ans - Keypair

# Please input the password:

# Ans - dappley

# New miner_address & pravte_key generated
# miner_address:  dYNe6tNN77NCJRKdZRvDXeL7uLVpYBGhJQ
# private_key:  97b60953ea0529f53831e922c229a15bb5fc8a3c9b067bc54d0d7eadb21c1c25
# Port info:
# Input nothing for default setting: 12341

# Ans - Nothing

# Seed:

# CAISICMUvaL/UxDELHpZiTbJ7subEtRverOR7XFndu4y/CUO

# db_path: Input nothing for default: ../bin/node6.db

# Ans - Nothing

# Rpc_port: Input nothing for default setting : 50051

# Ans - 50056

# Key: Input nothing to generate new key

# Ans - Nothing


#################### Update cli ports on All nodes ####################
  - name: Update node1 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50051'
    when: inventory_hostname in groups['NODE1']

  - name: Update node2 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50052'
    when: inventory_hostname in groups['NODE2']

  - name: Update node3 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50053'
    when: inventory_hostname in groups['NODE3']

  - name: Update node4 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50054'
    when: inventory_hostname in groups['NODE4']

  - name: Update node5 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50055'
    when: inventory_hostname in groups['NODE5']

  - name: Update node6 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50056'
    when: inventory_hostname in groups['NODE6']



#################### Update seed on All nodes ####################
  - name: Update node1 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node1.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE2
    when: inventory_hostname in groups['NODE1']

  - name: Update node2 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node2.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE2']

  - name: Update node3 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node3.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE3']

  - name: Update node4 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node4.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE4']

  - name: Update node5 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node5.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE5']


  - name: Update node6 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node6.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE6']


#################### Launch Blockchain ####################
  - name: Launch NODE1
    shell: ./dapp -f conf/node1.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE1']
    async: 60
    poll: 0

  - name: Launch NODE2
    shell: ./dapp -f conf/node2.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE2']
    async: 60
    poll: 0

  - name: Launch NODE3
    shell: ./dapp -f conf/node3.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE3']
    async: 60
    poll: 0

  - name: Launch NODE4
    shell: ./dapp -f conf/node4.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE4']
    async: 60
    poll: 0

  - name: Launch NODE5
    shell: ./dapp -f conf/node5.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE5']
    async: 60
    poll: 0

  - name: Launch NODE6
    shell: ./dapp -f conf/node6.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE6']
    async: 60
    poll: 0

  - name: Wait for blockchain initialization
    wait_for:
      timeout: 20

  - name: Wait til the blockchain reaches height of 10
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight
    until: (blockchainHeight.stdout_lines[1][17:-1])|int > (10)|int
    retries: 20
    delay: 10
    ignore_errors: true


#################### Terminate ####################
  - name: Wait til the blockchain terminates
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight
    until: blockchainHeight.stdout_lines[0][7:] == "server is not reachable!"
    retries: 20
    delay: 10
    ignore_errors: true

  - name: Remove /go-dappley/bin All Nodes
    shell: rm -r bin
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/
    ignore_errors: true

  # - name: Remove /go-dappley/dapp/bin Node
  #   shell: rm -r bin
  #   args:
  #     chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/
  #   ignore_errors: true