#################### Check NODE1 result ####################
- name: Create initialization result NODE1 - true
  shell: echo true > error_1.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE1'] and blockchainHeight.failed

- name: Create initialization result NODE1- false
  shell: echo false > error_1.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE1'] and not blockchainHeight.failed


#################### Check NODE2 result ####################
- name: Create initialization result NODE2 - true
  shell: echo true > error_2.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE2'] and blockchainHeight.failed

- name: Create initialization result NODE2 - false
  shell: echo false > error_2.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE2'] and not blockchainHeight.failed


#################### Check NODE3 result ####################
- name: Create initialization result NODE3 - true
  shell: echo true > error_3.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE3'] and blockchainHeight.failed

- name: Create initialization result NODE3 - false
  shell: echo false > error_3.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE3'] and not blockchainHeight.failed


#################### Check NODE4 result ####################
- name: Create initialization result NODE4 - true
  shell: echo true > error_4.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE4'] and blockchainHeight.failed

- name: Create initialization result NODE4 - false
  shell: echo false > error_4.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE4'] and not blockchainHeight.failed


#################### Check NODE5 result ####################
- name: Create initialization result NODE5 - true
  shell: echo true > error_5.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE5'] and blockchainHeight.failed

- name: Create initialization result NODE5 - false
  shell: echo false > error_5.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when: inventory_hostname in groups['NODE5'] and not blockchainHeight.failed


#################### Check NODE6 result ####################
- name: Create initialization result NODE6 - true
  shell: echo true > error_6.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE6' in groups"
  - node_number|int >= 6|int
  - inventory_hostname in groups['NODE6']
  - blockchainHeight.failed

- name: Create initialization result NODE6 - false
  shell: echo false > error_6.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE6' in groups"
  - node_number|int >= 6|int
  - inventory_hostname in groups['NODE6']
  - not blockchainHeight.failed


#################### Check NODE7 result ####################
- name: Create initialization result NODE7 - true
  shell: echo true > error_7.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE7' in groups"
  - node_number|int >= 7|int
  - inventory_hostname in groups['NODE7']
  - blockchainHeight.failed

- name: Create initialization result NODE7 - false
  shell: echo false > error_7.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE7' in groups"
  - node_number|int >= 7|int
  - inventory_hostname in groups['NODE7']
  - not blockchainHeight.failed

#################### Check NODE8 result ####################
- name: Create initialization result NODE8 - true
  shell: echo true > error_8.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE8' in groups"
  - node_number|int >= 8|int
  - inventory_hostname in groups['NODE8']
  - blockchainHeight.failed

- name: Create initialization result NODE8 - false
  shell: echo false > error_8.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE8' in groups"
  - node_number|int >= 8|int
  - inventory_hostname in groups['NODE8']
  - not blockchainHeight.failed

#################### Check NODE9 result ####################
- name: Create initialization result NODE9 - true
  shell: echo true > error_9.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE9' in groups"
  - node_number|int >= 9|int
  - inventory_hostname in groups['NODE9']
  - blockchainHeight.failed

- name: Create initialization result NODE9 - false
  shell: echo false > error_9.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE9' in groups"
  - node_number|int >= 9|int
  - inventory_hostname in groups['NODE9']
  - not blockchainHeight.failed

#################### Check NODE10 result ####################
- name: Create initialization result NODE10 - true
  shell: echo true > error_10.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE10' in groups"
  - node_number|int >= 10|int
  - inventory_hostname in groups['NODE10']
  - blockchainHeight.failed

- name: Create initialization result NODE10 - false
  shell: echo false > error_10.txt
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
  when:
  - "'NODE10' in groups"
  - node_number|int >= 10|int
  - inventory_hostname in groups['NODE10']
  - not blockchainHeight.failed

#################### Move initialization result ####################
- name: Move playbook test result to Jenkins - NODE1
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_1.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node1/
    flat: yes
  when: inventory_hostname in groups['NODE1']

- name: Move playbook test result to Jenkins - NODE2
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_2.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node2/
    flat: yes
  when: inventory_hostname in groups['NODE2']

- name: Move playbook test result to Jenkins - NODE3
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_3.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node3/
    flat: yes
  when: inventory_hostname in groups['NODE3']

- name: Move playbook test result to Jenkins - NODE4
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_4.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node4/
    flat: yes
  when: inventory_hostname in groups['NODE4']

- name: Move playbook test result to Jenkins - NODE5
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_5.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node5/
    flat: yes
  when: inventory_hostname in groups['NODE5']

- name: Move playbook test result to Jenkins - NODE6
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_6.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node6/
    flat: yes
  when:
  - "'NODE6' in groups"
  - node_number|int >= 6|int
  - inventory_hostname in groups['NODE6']

- name: Move playbook test result to Jenkins - NODE7
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_7.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node7/
    flat: yes
  when:
  - "'NODE7' in groups"
  - node_number|int >= 7|int
  - inventory_hostname in groups['NODE7']

- name: Move playbook test result to Jenkins - NODE8
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_8.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node8/
    flat: yes
  when:
  - "'NODE8' in groups"
  - node_number|int >= 8|int
  - inventory_hostname in groups['NODE8']

- name: Move playbook test result to Jenkins - NODE9
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_9.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node9/
    flat: yes
  when:
  - "'NODE9' in groups"
  - node_number|int >= 9|int
  - inventory_hostname in groups['NODE9']

- name: Move playbook test result to Jenkins - NODE10
  fetch:
    src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_10.txt
    dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node10/
    flat: yes
  when:
  - "'NODE10' in groups"
  - node_number|int >= 10|int
  - inventory_hostname in groups['NODE10']


#################### Terminate playbook when initialization returns error ####################
- meta: end_play
  when: blockchainHeight.failed