---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"

  roles:
#################### Roles ####################
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/make_build
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/initialize_async
      node_number: 6
      async_runtime: 130
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/blockchain_status_check
      node_number: 6

  tasks:
#################### Check producers ####################
  - name: Check Blockchain
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: BlockchainInfo

################### Check 4 producers ###################
  - name: Check producer 1-1
    fail:
      msg: "Expected '[' but returned {{ BlockchainInfo.stdout_lines[2] }}"
    when: BlockchainInfo.stdout_lines[2][-1:] != "["
    ignore_errors: true

  - name: Check producer 1-2
    fail:
      msg: "Expected 'dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa' but returned {{ BlockchainInfo.stdout_lines[3] }}"
    when: BlockchainInfo.stdout_lines[3][5:-2] != "dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa"
    ignore_errors: true

  - name: Check producer 1-3
    fail:
      msg: "Expected 'dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12' but returned {{ BlockchainInfo.stdout_lines[4] }}"
    when: BlockchainInfo.stdout_lines[4][5:-2] != "dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12"
    ignore_errors: true

  - name: Check producer 1-4
    fail:
      msg: "Expected 'dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C' but returned {{ BlockchainInfo.stdout_lines[5] }}"
    when: BlockchainInfo.stdout_lines[5][5:-2] != "dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C"
    ignore_errors: true

  - name: Check producer 1-5
    fail:
      msg: "Expected 'dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm' but returned {{ BlockchainInfo.stdout_lines[6] }}"
    when: BlockchainInfo.stdout_lines[6][5:-1] != "dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm"
    ignore_errors: true

  - name: Check producer 1-6
    fail:
      msg: "Expected ']' but returned {{ BlockchainInfo.stdout_lines[7] }}"
    when: BlockchainInfo.stdout_lines[7][-2:-1] != "]"
    ignore_errors: true

#################### Add then change ####################
  - name: Get Blockchain Height
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight

  - name: Add Producer
    shell: ./cli addProducer -address dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh -height {{ (blockchainHeight.stdout_lines[1][17:-1])|int + 5|int }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: test_result
    when: inventory_hostname in groups['NODE1']

  - name: Wait for next block
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: new_blockchainHeight
    until: (new_blockchainHeight.stdout_lines[1][17:-1])|int > (blockchainHeight.stdout_lines[1][17:-1])|int + 1|int
    retries: 100
    delay: 1
    ignore_errors: true

  - name: Change Producer
    shell: ./cli changeProducer -address dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3 -height {{ (blockchainHeight.stdout_lines[1][17:-1])|int + 5|int }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: test_result
    when: inventory_hostname in groups['NODE1']

  - name: Wait for methods to deploy
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: new_blockchainHeight
    until: (new_blockchainHeight.stdout_lines[1][17:-1])|int > (blockchainHeight.stdout_lines[1][17:-1])|int + 5|int
    retries: 5
    delay: 10
    ignore_errors: true

#################### Check producers ####################
  - name: Check Blockchain
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: BlockchainInfo

################### Check 4 producers ###################
  - name: Check producer 1-1
    fail:
      msg: "Expected '[' but returned {{ BlockchainInfo.stdout_lines[2] }}"
    when: BlockchainInfo.stdout_lines[2][-1:] != "["
    ignore_errors: true

  - name: Check producer 1-2
    fail:
      msg: "Expected 'dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3' but returned {{ BlockchainInfo.stdout_lines[3] }}"
    when: BlockchainInfo.stdout_lines[3][5:-2] != "dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3"
    ignore_errors: true

  - name: Check producer 1-3
    fail:
      msg: "Expected 'dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12' but returned {{ BlockchainInfo.stdout_lines[4] }}"
    when: BlockchainInfo.stdout_lines[4][5:-2] != "dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12"
    ignore_errors: true

  - name: Check producer 1-4
    fail:
      msg: "Expected 'dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C' but returned {{ BlockchainInfo.stdout_lines[5] }}"
    when: BlockchainInfo.stdout_lines[5][5:-2] != "dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C"
    ignore_errors: true

  - name: Check producer 1-5
    fail:
      msg: "Expected 'dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm' but returned {{ BlockchainInfo.stdout_lines[6] }}"
    when: BlockchainInfo.stdout_lines[6][5:-1] != "dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm"
    ignore_errors: true

  - name: Check producer 1-6
    fail:
      msg: "Expected ']' but returned {{ BlockchainInfo.stdout_lines[7] }}"
    when: BlockchainInfo.stdout_lines[7][-2:-1] != "]"
    ignore_errors: true

#################### Terminate ####################
- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"
  roles:
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/terminate_async