---

- hosts: all
  become: true
  tasks:

  - name: Check directory exists
    stat:
      path: /home/ubuntu/go
    register: go_directory

  - name: Create go-dappley directories
    shell: mkdir go go/src go/pkg go/bin go/src/github.com go/src/github.com/dappley
    when: go_directory.stat.exists == false

  - name: Clone the go-dappley repository
    ansible.builtin.git:
      repo: https://github.com/dappley/go-dappley.git
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/

  - name: Update apt
    apt:
      update_cache: yes

  - name: Upgrade apt
    apt:
      upgrade: dist

  - name: Install g++
    apt:
      name: g++

  - name: Install make
    apt:
      name: make

  - name: Download go.zip
    get_url:
      url: https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
      dest: /home/ubuntu/

  - name: Extract go.tgz
    ansible.builtin.unarchive:
      src: /home/ubuntu/go1.16.3.linux-amd64.tar.gz
      dest: /usr/local/
      remote_src: yes

  - name: Add lines to .bashrc
    lineinfile:
      path: /home/ubuntu/.bashrc
      state: present
      line: "{{ item }}"
    with_items:
    - ' '
    - '# Test variable'
    - 'export TEST="This is a test variable"'
    - 'export TESTPATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin'
    - 'export OGPATH=$PATH'
    - ' '
    - '# Add go to path'
    - 'export GOPATH=$HOME/go'
    - 'export GOROOT=/usr/local/go'
    - 'export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin'
    
    # - 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin'

  - name:
    become: true
    become_user: ubuntu
    shell: echo $TEST $TESTPATH $OGPATH $GOPATH $GOROOT $PATH 
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    register: GOENV

  - debug:
      msg: "{{ GOENV }}"

  - name: Grant permission
    file:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley
      owner: ubuntu
      group: ubuntu
      recurse: yes

  - debug:
      msg: "{{ GOENV }}"

  # - name: Whoami
  #   command: whoami
  #   register: whoami

  # - debug:
  #     msg: "{{ whoami }}"

  # - name:
  #   become: true
  #   become_user: ubuntu
  #   shell: make build
  #   args:
  #     chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley


  # - name: Make build
    # shell: make build
    # args:
    #   chdir: /home/ubuntu/go-dappley

    # become: yes
    # become_method: su
    # become_user: ubuntu
    # shell: make build
    # args:
    #   chdir: /home/ubuntu/go-dappley

#     become: yes
#     become_method: su
#     become_user: ubuntu
#     make:
#       chdir: /home/ubuntu/go-dappley
#       target: build
#       file: /home/ubuntu/go-dappley/Makefile


    # make:
    #   chdir: /home/ubuntu/go-dappley
    #   target: build
    #   file: /home/ubuntu/go-dappley/Makefile


  #   make:
  #     chdir: /home/ubuntu/go-dappley