---

- hosts: all
  become: true
  tasks:

  - name: Clone the go-dappley repository
    ansible.builtin.git:
      repo: https://github.com/dappley/go-dappley.git
      dest: /home/ubuntu/go-dappley/

  - name: Update apt
    apt:
      update_cache: yes

  - name: Upgrade apt
    apt:
      upgrade: dist

  - name: Install g++
    apt:
      name: g++

  - name: Install make
    apt:
      name: make

  - name: Download go.zip
    get_url:
      url: https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
      dest: /home/ubuntu/

  # - name: Install golang

  # - name: Grant permission to go-dapply

  # - name: Make build