---

- hosts: all
  become: true
  tasks: 

  # - name: Create go-dappley directory
  #   file:
  #     path: /home/ubuntu/go-dappley
  #     state: directory

  - name: Clone the go-dappley repository
    ansible.builtin.git:
      repo: https://github.com/dappley/go-dappley.git
      dest: /home/ubuntu/go-dappley/