---

- hosts: all
  become: true
  tasks: 

  - name: Clone the go-dappley repository
    ansible.builtin.git:
      repo: https://github.com/dappley/go-dappley.git
      dest: /home/ubuntu/go-dappley/

  - name: Update apt
    shell: apt dist-upgrade -y

  - name: Install g++
    shell: apt install g++ -y

  - name: Install make
    apt:
      name: make

  # - name: Install golang

  # - name: Grant permission to go-dapply

  # - name: Make build