---

- hosts: all
  become: true

  tasks:
  - name: Check directory exists
    stat:
      path: /home/ubuntu/go
    register: go_directory

  - name: Create go-dappley directories
    shell: mkdir go go/src go/pkg go/bin go/src/github.com go/src/github.com/dappley
    when: go_directory.stat.exists == false

  - name: Clone the go-dappley repository
    ansible.builtin.git:
      repo: https://github.com/dappley/go-dappley.git
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/

  - name: Update apt
    apt:
      update_cache: yes

  - name: Upgrade apt
    apt:
      upgrade: dist

  - name: Install g++
    apt:
      name: g++

  - name: Install make
    apt:
      name: make

  - name: Download go.zip
    get_url:
      url: https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
      dest: /home/ubuntu/

  - name: Extract go.tgz
    ansible.builtin.unarchive:
      src: /home/ubuntu/go1.16.3.linux-amd64.tar.gz
      dest: /usr/local/
      remote_src: yes

  - name: Add lines to .bashrc
    lineinfile:
      path: /home/ubuntu/.bashrc
      state: present
      line: "{{ item }}"
    with_items:
    - ' '
    - '# Add go to path'
    - 'export GOPATH=$HOME/go'
    - 'export GOROOT=/usr/local/go'
    - 'export PATH=$PATH:$GOROOT/bin:$GOPATH/bin'

  - name: Grant permission
    file:
      path: /home/ubuntu/go/
      owner: ubuntu
      group: ubuntu
      recurse: yes