---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"
  vars:
    account1: dZmRE2UWEnB1hG85n9bUsZ7Z14Pp1ZFPPK
    account2: dcbtkT5UattbmRZqPqP6yobYy5mMi8HiHq

  tasks:
  - name: Accounts.dat to Node1
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-ansible-accounts/node1/accounts.dat
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/bin/
    when: inventory_hostname in groups['NODE1']

  - name: Accounts.dat to Node2
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-ansible-accounts/node2/accounts.dat
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/bin/
    when: inventory_hostname in groups['NODE2']

  - name: Check go environment
    shell: echo $GOPATH && echo $GOROOT && echo $PATH
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    register: GOENV

  - debug:
      msg: "{{ GOENV.stdout_lines }}"

  - name: Check go version
    shell: go version
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    register: GOVERSION

  - debug:
      msg: "{{ GOVERSION.stdout_lines }}"

  - name: Make build
    make:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
      target: build
      file: /home/ubuntu/go/src/github.com/dappley/go-dappley/Makefile

  - name: Update node1 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50051'
    when: inventory_hostname in groups['NODE1']

  - name: Update node2 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50052'
    when: inventory_hostname in groups['NODE2']

  - name: Update node3 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50053'
    when: inventory_hostname in groups['NODE3']

  - name: Update node4 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50054'
    when: inventory_hostname in groups['NODE4']

  - name: Update node5 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50055'
    when: inventory_hostname in groups['NODE5']

  - name: Update node1 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node1.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE2
    when: inventory_hostname in groups['NODE1']

  - name: Update node2 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node2.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE2']

  - name: Update node3 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node3.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE3']

  - name: Update node4 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node4.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE4']

  - name: Update node5 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node5.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE5']

  - name: Launch node1
    shell: ./dapp -f conf/node1.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE1']
    async: 1000
    poll: 0

  - name: Launch node2
    shell: ./dapp -f conf/node2.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE2']
    async: 1000
    poll: 0

  - name: Launch node3
    shell: ./dapp -f conf/node3.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE3']
    async: 1000
    poll: 0

  - name: Launch node4
    shell: ./dapp -f conf/node4.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE4']
    async: 1000
    poll: 0

  - name: Launch node5
    shell: ./dapp -f conf/node5.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE5']
    async: 1000
    poll: 0

  - name: Wait 10 seconds to launch blockchain
    wait_for:
      timeout: 10

  - name: Wait til the blockchain reaches height of 10
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight
    until: (blockchainHeight.stdout_lines[1][17:]|replace(',',''))|int > (10)|int
    retries: 1000
    delay: 10

  - debug:
      msg: "Blockchain height: {{ blockchainHeight.stdout_lines[1][17:]|replace(',','') }}"

  - name: Check account1 balance
    shell: ./cli getBalance -address {{ account1 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account1Balance

  - debug:
      msg: 'Account1 balance: {{ account1Balance.stdout_lines[0][16:] }}'

  - name: Check account2 balance
    shell: ./cli getBalance -address {{ account2 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account2Balance

  - debug:
      msg: 'Account2 blanace: {{ account2Balance.stdout_lines[0][16:] }}'

  - name: Send money to account1
    shell: ./cli sendFromMiner -to {{ account1 }} -amount 10000
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    when: inventory_hostname in groups['NODE1']

  - name: Wait 10 seconds to complete transaction
    wait_for:
      timeout: 10

  - name: Check account1 balance
    shell: ./cli getBalance -address {{ account1 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account1Balance

  - debug:
      msg: 'Account1 balance: {{ account1Balance.stdout_lines[0][16:] }}'

  - name: Check account2 balance
    shell: ./cli getBalance -address {{ account2 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account2Balance

  - debug:
      msg: 'Account2 blanace: {{ account2Balance.stdout_lines[0][16:] }}'

  - name: Send money from account1 to account2
    shell: ./cli send -from {{ account1 }} -to {{ account2 }} -amount 5000
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    when: inventory_hostname in groups['NODE1']

  - name: Wait 10 seconds to complete transaction
    wait_for:
      timeout: 10

  - name: Check account1 balance
    shell: ./cli getBalance -address {{ account1 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account1Balance

  - debug:
      msg: 'Account1 balance: {{ account1Balance.stdout_lines[0][16:] }}'

  - name: Account1 balance test
    fail:
     msg: "Expected 5000 but returned {{ account1Balance.stdout_lines[0][16:] }}"
    when: account1Balance.stdout_lines[0][16:]|int != 5000|int
    ignore_errors: true

  - name: Check account2 balance
    shell: ./cli getBalance -address {{ account2 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account2Balance

  - debug:
      msg: 'Account2 blanace: {{ account2Balance.stdout_lines[0][16:] }}'

  - name: Account2 balance test
    fail:
     msg: "Expected 5000 but returned {{ account2Balance.stdout_lines[0][16:] }}"
    when: account2Balance.stdout_lines[0][16:]|int != 5000|int
    ignore_errors: true

  - name: Remove /go-dappley/bin All Nodes
    shell: rm -r bin
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/

  - name: Remove /go-dappley/dapp/bin Node1
    shell: rm -r bin
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/
    when: inventory_hostname in groups['NODE1']

  - name: Remove /go-dappley/dapp/bin Node2
    shell: rm -r bin
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/
    when: inventory_hostname in groups['NODE2']