---

- hosts: all
  become: true
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"

  tasks:
  - name:
    become: true
    become_user: ubuntu
    shell: echo $GOPATH && echo $GOROOT && echo $PATH
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    register: GOENV

  - debug:
      msg: "{{ GOENV }}"

  - name:
    become: true
    become_user: ubuntu
    shell: go version
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    register: GOVERSION

  - debug:
      msg: "{{ GOVERSION }}"

# - name: Whoami
#   command: whoami
#   register: whoami

# - debug:
#     msg: "{{ whoami }}"

# - name: Make build
#   become: true
#   become_user: ubuntu
#   shell: make build
#   args:
#     chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley


# - name: Make build
#   shell: make build
#   args:
#     chdir: /home/ubuntu/go-dappley

# - name: Make build
#   become: yes
#   become_method: su
#   become_user: ubuntu
#   shell: make build
#   args:
#     chdir: /home/ubuntu/go-dappley

# - name: Make build
#   become: yes
#   become_method: su
#   become_user: ubuntu
#   make:
#    chdir: /home/ubuntu/go-dappley
#    target: build
#    file: /home/ubuntu/go-dappley/Makefile

# - name: Make build
#   make:
#     chdir: /home/ubuntu/go-dappley
#     target: build
#     file: /home/ubuntu/go-dappley/Makefile

# - name: Make build
#   make:
#     chdir: /home/ubuntu/go-dappley