---

- hosts: all
  become: true
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"

  tasks:
  - name: Check go environment
    become: true
    become_user: ubuntu
    shell: echo $GOPATH && echo $GOROOT && echo $PATH
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    register: GOENV

  - debug:
      msg: "{{ GOENV }}"

  - name: Check go version
    become: true
    become_user: ubuntu
    shell: go version
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    register: GOVERSION

  - debug:
      msg: "{{ GOVERSION }}"

  - name: Make build
    make:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
      target: build
      file: /home/ubuntu/go/src/github.com/dappley/go-dappley/Makefile

  - name: Update port in cli
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50050'
      replace: 'port: 50051'