---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"
  vars:
    account1: account_1_address
    account2: account_2_address
    est_gasPrice: 0

  roles:
#################### Roles ####################
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/copy_account_address
      node_number: 1
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/copy_account_address
      node_number: 2
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/make_build
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/initialize_async
      node_number: 5
      async_runtime: 140
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/blockchain_status_check
      node_number: 5
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/add_producerAccount

  tasks:
#################### Add balance to account1 ####################
  - name: Send money to account1
    shell: ./cli send -from dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa -to {{ account1 }} -amount 100000
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    when: inventory_hostname in groups['NODE1']

  - name: Wait 10 seconds to complete transaction
    wait_for:
      timeout: 10

  - name: Check account1 balance
    shell: ./cli getBalance -address {{ account1 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account1Balance_1

  - name: Check account2 balance
    shell: ./cli getBalance -address {{ account2 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account2Balance_1

#################### Create smart contract 1 ####################
  - name: Estimate Gas Price
    shell: ./cli estimateGas -from {{ account1 }} -amount 100 -tip 0 -gasLimit 30000 -gasPrice 1 -file ../jslib/step_recorder.js
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: estimated_gas_price
    when: inventory_hostname in groups['NODE1']

  - name: set estimated gas price
    set_fact: est_gasPrice="{{ estimated_gas_price.stdout_lines[0].split(":")[1] | int }}"
    when: inventory_hostname in groups['NODE1']

  - name: Create smart contract 1
    shell: ./cli send -from {{ account1 }} -amount 100 -tip 0 -gasLimit 30000 -gasPrice 1 -file ../jslib/step_recorder.js
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: smart_contract_1
    when: inventory_hostname in groups['NODE1']

  - name: Wait 10 seconds to complete transaction
    wait_for:
      timeout: 10

#################### Check account1 && account2 balance ####################
  - name: Check account1 balance
    shell: ./cli getBalance -address {{ account1 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account1Balance_2

  - name: Account1 balance test
    fail:
     msg: "Expected to return {{ account1Balance_1.stdout_lines[0][16:]|int - 100|int - est_gasPrice|int }}, but returned {{ account1Balance_2.stdout_lines[0][16:] }}."
    ignore_errors: true
    when: inventory_hostname in groups['NODE1'] and account1Balance_2.stdout_lines[0][16:]|int != account1Balance_1.stdout_lines[0][16:]|int - 100|int - est_gasPrice|int

  - name: Check account2 balance
    shell: ./cli getBalance -address {{ account2 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account2Balance_2

  - name: Account2 balance test
    fail:
     msg: "Expected {{ account2Balance_1.stdout_lines[0][16:]|int }} but returned {{ account2Balance_2.stdout_lines[0][16:] }}"
    when: inventory_hostname in groups['NODE1'] and account2Balance_2.stdout_lines[0][16:]|int != account2Balance_1.stdout_lines[0][16:]|int
    ignore_errors: true

#################### Create smart contract 2 ####################
  - name: Estimate Gas Price
    shell: ./cli estimateGas -from {{ account1 }} -amount 100 -tip 0 -gasLimit 30000 -gasPrice 1 -file ../jslib/step_recorder.js
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: estimated_gas_price
    when: inventory_hostname in groups['NODE1']

  - name: set estimated gas price
    set_fact: est_gasPrice="{{ estimated_gas_price.stdout_lines[0].split(":")[1] | int }}"
    when: inventory_hostname in groups['NODE1']

  - name: Create smart contract 2
    shell: ./cli send -from {{ account1 }} -amount 100 -tip 0 -gasLimit 30000 -gasPrice 1 -file ../jslib/step_recorder.js
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: smart_contract_2
    when: inventory_hostname in groups['NODE1']

  - name: Wait 10 seconds to complete transaction
    wait_for:
      timeout: 10

#################### Check account1 && account2 balance ####################
  - name: Check account1 balance
    shell: ./cli getBalance -address {{ account1 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account1Balance_3

  - name: Account1 balance test
    fail:
     msg: "Expected to return {{ account1Balance_2.stdout_lines[0][16:]|int - 100|int - est_gasPrice|int}}, but returned {{ account1Balance_3.stdout_lines[0][16:] }}."
    ignore_errors: true
    when: inventory_hostname in groups['NODE1'] and account1Balance_3.stdout_lines[0][16:]|int != account1Balance_2.stdout_lines[0][16:]|int - 100|int - est_gasPrice|int

  - name: Check account2 balance
    shell: ./cli getBalance -address {{ account2 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account2Balance_3

  - name: Account2 balance test
    fail:
     msg: "Expected {{ account2Balance_2.stdout_lines[0][16:]|int }} but returned {{ account2Balance_3.stdout_lines[0][16:] }}"
    when: account2Balance_3.stdout_lines[0][16:]|int != account2Balance_2.stdout_lines[0][16:]|int
    ignore_errors: true

#################### Estimate Gas 1 ####################
  - name: Estimate Gas 1
    shell: ./cli estimateGas -from {{ account1 }} -to {{ smart_contract_1.stdout_lines[0][18:] }} -amount 10 -tip 0 -gasLimit 30000 -gasPrice 1 -data '{"function":"record","args":["account_2_address","5000"]}'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: estimate_gas
    when: inventory_hostname in groups['NODE1']

#################### Deploy smart contract ####################
  - name: Deploy smart contract with estimated amount
    shell: ./cli send -from {{ account1 }} -to {{ smart_contract_1.stdout_lines[0][18:] }} -amount 10 -tip 0 -gasLimit {{ est_gasPrice }} -gasPrice 1 -data '{"function":"record","args":["account_2_address","5000"]}'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: deploy_smart_contract_1
    when: inventory_hostname in groups['NODE1']

  - name: Wait 10 seconds to complete transaction
    wait_for:
      timeout: 10

#################### Check account1 && account2 balance ####################
  - name: Check account1 balance
    shell: ./cli getBalance -address {{ account1 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account1Balance_4

  - name: Account1 balance test
    fail:
     msg: "Expected the value to be {{ account1Balance_3.stdout_lines[0][16:]|int - est_gasPrice|int - 10|int }}, but returned {{ account1Balance_4.stdout_lines[0][16:] }}."
    ignore_errors: true
    when: inventory_hostname in groups['NODE1'] and account1Balance_4.stdout_lines[0][16:]|int != account1Balance_3.stdout_lines[0][16:]|int - est_gasPrice|int - 10|int

  - name: Check account2 balance
    shell: ./cli getBalance -address {{ account2 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account2Balance_4

  - name: Account2 balance test
    fail:
     msg: "Expected {{ account2Balance_3.stdout_lines[0][16:]|int + 5000|int }} but returned {{ account2Balance_4.stdout_lines[0][16:] }}"
    when: account2Balance_4.stdout_lines[0][16:]|int != account2Balance_3.stdout_lines[0][16:]|int + 5000|int
    ignore_errors: true

#################### Estimate Gas 2 ####################
  - name: Estimate Gas 2
    shell: ./cli estimateGas -from {{ account1 }} -to {{ smart_contract_2.stdout_lines[0][18:] }} -amount 10 -tip 0 -gasLimit 30000 -gasPrice 1 -data '{"function":"record","args":["account_2_address","5000"]}'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: estimate_gas
    when: inventory_hostname in groups['NODE1']

#################### Deploy smart contract ####################
  - name: Deploy smart contract with estimated amount
    shell: ./cli send -from {{ account1 }} -to {{ smart_contract_2.stdout_lines[0][18:] }} -amount 10 -tip 0 -gasLimit {{ est_gasPrice }} -gasPrice 1 -data '{"function":"record","args":["account_2_address","5000"]}'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: deploy_smart_contract_2
    when: inventory_hostname in groups['NODE1']

  - name: Wait 10 seconds to complete transaction
    wait_for:
      timeout: 10

#################### Check account1 && account2 balance ####################
  - name: Check account1 balance
    shell: ./cli getBalance -address {{ account1 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account1Balance_5

  - name: Account1 balance test
    fail:
     msg: "Expected the value to be {{ account1Balance_4.stdout_lines[0][16:]|int - est_gasPrice|int - 10|int }}, but returned {{ account1Balance_5.stdout_lines[0][16:] }}."
    ignore_errors: true
    when: inventory_hostname in groups['NODE1'] and account1Balance_5.stdout_lines[0][16:]|int != account1Balance_4.stdout_lines[0][16:]|int - 2.stdout_lines[0][19:]|int - 10|int

  - name: Check account2 balance
    shell: ./cli getBalance -address {{ account2 }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: account2Balance_5

  - name: Account2 balance test
    fail:
     msg: "Expected {{ account2Balance_4.stdout_lines[0][16:] + 5000|int }}, but returned {{ account2Balance_5.stdout_lines[0][16:] }}"
    when: account2Balance_5.stdout_lines[0][16:]|int != account2Balance_4.stdout_lines[0][16:]|int + 5000|int
    ignore_errors: true

#################### Terminate ####################
- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"
  roles:
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/terminate_async