- name: Launch NODE1
  shell: ./dapp -f conf/node1.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when: inventory_hostname in groups['NODE1']
  async: '{{ async_runtime }}'
  poll: 0

- name: Launch NODE2
  shell: ./dapp -f conf/node2.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when: inventory_hostname in groups['NODE2']
  async: '{{ async_runtime }}'
  poll: 0

- name: Launch NODE3
  shell: ./dapp -f conf/node3.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when: inventory_hostname in groups['NODE3']
  async: '{{ async_runtime }}'
  poll: 0

- name: Launch NODE4
  shell: ./dapp -f conf/node4.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when: inventory_hostname in groups['NODE4']
  async: '{{ async_runtime }}'
  poll: 0

- name: Launch NODE5
  shell: ./dapp -f conf/node5.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when: inventory_hostname in groups['NODE5']
  async: '{{ async_runtime }}'
  poll: 0

- name: Launch NODE6
  shell: ./dapp -f conf/node6.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when:
  - "'NODE6' in groups"
  - node_number|int >= 6|int
  - inventory_hostname in groups['NODE6']
  async: '{{ async_runtime }}'
  poll: 0

- name: Launch NODE7
  shell: ./dapp -f conf/node7.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when:
  - "'NODE7' in groups"
  - node_number|int >= 7|int
  - inventory_hostname in groups['NODE7']
  async: '{{ async_runtime }}'
  poll: 0

- name: Launch NODE8
  shell: ./dapp -f conf/node8.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when:
  - "'NODE8' in groups"
  - node_number|int >= 8|int
  - inventory_hostname in groups['NODE8']
  async: '{{ async_runtime }}'
  poll: 0

- name: Launch NODE9
  shell: ./dapp -f conf/node9.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when:
  - "'NODE9' in groups"
  - node_number|int >= 9|int
  - inventory_hostname in groups['NODE9']
  async: '{{ async_runtime }}'
  poll: 0

- name: Launch NODE10
  shell: ./dapp -f conf/node10.conf
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
  when:
  - "'NODE10' in groups"
  - node_number|int >= 10|int
  - inventory_hostname in groups['NODE10']
  async: '{{ async_runtime }}'
  poll: 0

- name: Wait for blockchain initialization
  wait_for:
    timeout: 20

- name: Wait til the blockchain reaches height of 10
  shell: ./cli getBlockchainInfo
  args:
    chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
  register: blockchainHeight
  until: (blockchainHeight.stdout_lines[1][17:-1])|int > (10)|int
  retries: 20
  delay: 10
  ignore_errors: true