---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"

  tasks:
#################### Send Accounts.dat ####################
  - name: Make build
    make:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
      target: build
      file: /home/ubuntu/go/src/github.com/dappley/go-dappley/Makefile


#################### Launch Blockchain ####################
  - name: Launch NODE1
    shell: ./dapp -f conf/node1.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE1']
    async: 2000
    poll: 0

  - name: Launch NODE2
    shell: ./dapp -f conf/node2.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE2']
    async: 2000
    poll: 0

  - name: Launch NODE3
    shell: ./dapp -f conf/node3.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE3']
    async: 2000
    poll: 0

  - name: Launch NODE4
    shell: ./dapp -f conf/node4.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE4']
    async: 2000
    poll: 0

  - name: Launch NODE5
    shell: ./dapp -f conf/node5.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE5']
    async: 2000
    poll: 0

  - name: Launch NODE6
    shell: ./dapp -f conf/node6.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE6']
    async: 2000
    poll: 0

  - name: Wait for blockchain initialization
    wait_for:
      timeout: 20

  - name: Wait til the blockchain reaches height of 10
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight
    until: (blockchainHeight.stdout_lines[1][17:-1])|int > (10)|int
    retries: 20
    delay: 10
    ignore_errors: true


#################### Check NODE1 result ####################
  - name: Create initialization result NODE1 - true
    shell: echo true > error_1.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE1'] and blockchainHeight.failed

  - name: Create initialization result NODE1- false
    shell: echo false > error_1.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE1'] and not blockchainHeight.failed


#################### Check NODE2 result ####################
  - name: Create initialization result NODE2 - true
    shell: echo true > error_2.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE2'] and blockchainHeight.failed

  - name: Create initialization result NODE2 - false
    shell: echo false > error_2.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE2'] and not blockchainHeight.failed


#################### Check NODE3 result ####################
  - name: Create initialization result NODE3 - true
    shell: echo true > error_3.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE3'] and blockchainHeight.failed

  - name: Create initialization result NODE3 - false
    shell: echo false > error_3.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE3'] and not blockchainHeight.failed


#################### Check NODE4 result ####################
  - name: Create initialization result NODE4 - true
    shell: echo true > error_4.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE4'] and blockchainHeight.failed

  - name: Create initialization result NODE4 - false
    shell: echo false > error_4.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE4'] and not blockchainHeight.failed


#################### Check NODE5 result ####################
  - name: Create initialization result NODE5 - true
    shell: echo true > error_5.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE5'] and blockchainHeight.failed

  - name: Create initialization result NODE5 - false
    shell: echo false > error_5.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE5'] and not blockchainHeight.failed


#################### Check NODE6 result ####################
  - name: Create initialization result NODE6 - true
    shell: echo true > error_6.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE6'] and blockchainHeight.failed

  - name: Create initialization result NODE6 - false
    shell: echo false > error_6.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
    when: inventory_hostname in groups['NODE6'] and not blockchainHeight.failed


#################### Move initialization result ####################
  - name: Move playbook test result to Jenkins - NODE1
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_1.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node1/
      flat: yes
    when: inventory_hostname in groups['NODE1']

  - name: Move playbook test result to Jenkins - NODE2
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_2.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node2/
      flat: yes
    when: inventory_hostname in groups['NODE2']

  - name: Move playbook test result to Jenkins - NODE3
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_3.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node3/
      flat: yes
    when: inventory_hostname in groups['NODE3']

  - name: Move playbook test result to Jenkins - NODE4
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_4.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node4/
      flat: yes
    when: inventory_hostname in groups['NODE4']

  - name: Move playbook test result to Jenkins - NODE5
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_5.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node5/
      flat: yes
    when: inventory_hostname in groups['NODE5']

  - name: Move playbook test result to Jenkins - NODE6
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/error_6.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/playbook_error/node6/
      flat: yes
    when: inventory_hostname in groups['NODE6']


#################### Terminate playbook when initialization returns error ####################
  - meta: end_play
    when: blockchainHeight.failed


#################### Check producers ####################
  - name: Check Blockchain
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: BlockchainInfo

  - debug:
      msg: '{{ BlockchainInfo }}'


################### Check 6 producers ###################
  - name: Check producer 1-1
    fail:
      msg: "Expected '[' but returned {{ BlockchainInfo.stdout_lines[2] }}"
    when: BlockchainInfo.stdout_lines[2][-1:] != "["
    ignore_errors: true

  - name: Check producer 1-2
    fail:
      msg: "Expected 'dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa' but returned {{ BlockchainInfo.stdout_lines[3] }}"
    when: BlockchainInfo.stdout_lines[3][5:-2] != "dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa"
    ignore_errors: true

  - name: Check producer 1-3
    fail:
      msg: "Expected 'dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12' but returned {{ BlockchainInfo.stdout_lines[4] }}"
    when: BlockchainInfo.stdout_lines[4][5:-2] != "dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12"
    ignore_errors: true

  - name: Check producer 1-4
    fail:
      msg: "Expected 'dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C' but returned {{ BlockchainInfo.stdout_lines[5] }}"
    when: BlockchainInfo.stdout_lines[5][5:-2] != "dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C"
    ignore_errors: true

  - name: Check producer 1-5
    fail:
      msg: "Expected 'dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm' but returned {{ BlockchainInfo.stdout_lines[6] }}"
    when: BlockchainInfo.stdout_lines[6][5:-2] != "dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm"
    ignore_errors: true

  - name: Check producer 1-6
    fail:
      msg: "Expected 'dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3' but returned {{ BlockchainInfo.stdout_lines[7] }}"
    when: BlockchainInfo.stdout_lines[7][5:-2] != "dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3"
    ignore_errors: true

  - name: Check producer 1-7
    fail:
      msg: "Expected 'dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh' but returned {{ BlockchainInfo.stdout_lines[8] }}"
    when: BlockchainInfo.stdout_lines[8][5:-1] != "dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh"
    ignore_errors: true

  - name: Check producer 1-8
    fail:
      msg: "Expected ']' but returned {{ BlockchainInfo.stdout_lines[9] }}"
    when: BlockchainInfo.stdout_lines[9][-2:-1] != "]"
    ignore_errors: true


#################### Remove One Producer ####################
  - name: Get Blockchain Height
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight

  - name: Remove Producer
    shell: ./cli deleteProducer -height {{ (blockchainHeight.stdout_lines[1][17:-1])|int + 2|int }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: test_result
    when: inventory_hostname in groups['NODE1']

  - debug:
      msg: '{{ test_result }}'
    when: inventory_hostname in groups['NODE1']

  - name: Test
    fail:
      msg: "Expected an error message about the maximum producer, but returned {{ test_result }}"
    when: inventory_hostname in groups['NODE1'] and test_result.stdout != "Producer will be delete."
    ignore_errors: true

  - name: Wait til the producer is removed
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: new_blockchainHeight
    until: (new_blockchainHeight.stdout_lines[1][17:-1])|int > (blockchainHeight.stdout_lines[1][17:-1])|int + 2|int
    retries: 5
    delay: 10
    ignore_errors: true


#################### Check producers ####################
  - name: Check Blockchain
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: BlockchainInfo

  - debug:
      msg: '{{ BlockchainInfo }}'


################### Check 5 producers ###################
  - name: Check producer 2-1
    fail:
      msg: "Expected '[' but returned {{ BlockchainInfo.stdout_lines[2] }}"
    when: BlockchainInfo.stdout_lines[2][-1:] != "["
    ignore_errors: true

  - name: Check producer 2-2
    fail:
      msg: "Expected 'dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12' but returned {{ BlockchainInfo.stdout_lines[3] }}"
    when: BlockchainInfo.stdout_lines[3][5:-2] != "dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12"
    ignore_errors: true

  - name: Check producer 2-3
    fail:
      msg: "Expected 'dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C' but returned {{ BlockchainInfo.stdout_lines[4] }}"
    when: BlockchainInfo.stdout_lines[4][5:-2] != "dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C"
    ignore_errors: true

  - name: Check producer 2-4
    fail:
      msg: "Expected 'dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm' but returned {{ BlockchainInfo.stdout_lines[5] }}"
    when: BlockchainInfo.stdout_lines[5][5:-2] != "dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm"
    ignore_errors: true

  - name: Check producer 2-5
    fail:
      msg: "Expected 'dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3' but returned {{ BlockchainInfo.stdout_lines[6] }}"
    when: BlockchainInfo.stdout_lines[6][5:-2] != "dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3"
    ignore_errors: true

  - name: Check producer 2-6
    fail:
      msg: "Expected 'dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh' but returned {{ BlockchainInfo.stdout_lines[7] }}"
    when: BlockchainInfo.stdout_lines[7][5:-1] != "dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh"
    ignore_errors: true

  - name: Check producer 2-7
    fail:
      msg: "Expected ']' but returned {{ BlockchainInfo.stdout_lines[8] }}"
    when: BlockchainInfo.stdout_lines[8][-2:-1] != "]"
    ignore_errors: true


#################### Check Blockchain Height ####################
  - name: Wait til the blockchain reaches height of 20
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight
    until: (blockchainHeight.stdout_lines[1][17:-1])|int > (20)|int
    retries: 20
    delay: 10
    ignore_errors: true


#################### Remove Another Producer ####################
  - name: Get Blockchain Height
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight

  - name: Remove Producer
    shell: ./cli deleteProducer -height {{ (blockchainHeight.stdout_lines[1][17:-1])|int + 2|int }}
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: test_result
    when: inventory_hostname in groups['NODE2']

  - debug:
      msg: '{{ test_result }}'
    when: inventory_hostname in groups['NODE2']

  - name: Test
    fail:
      msg: "Expected an error message about the maximum producer, but returned {{ test_result }}"
    when: inventory_hostname in groups['NODE2'] and test_result.stdout != "Producer will be delete."
    ignore_errors: true

  - name: Wait til the producer is removed
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: new_blockchainHeight
    until: (new_blockchainHeight.stdout_lines[1][17:-1])|int > (blockchainHeight.stdout_lines[1][17:-1])|int + 2|int
    retries: 5
    delay: 10
    ignore_errors: true


#################### Check producers ####################
  - name: Check Blockchain
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: BlockchainInfo

  - debug:
      msg: '{{ BlockchainInfo }}'


################### Check 4 producers ####################
  - name: Check producer 3-1
    fail:
      msg: "Expected '[' but returned {{ BlockchainInfo.stdout_lines[2] }}"
    when: BlockchainInfo.stdout_lines[2][-1:] != "["
    ignore_errors: true

  - name: Check producer 3-2
    fail:
      msg: "Expected 'dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C' but returned {{ BlockchainInfo.stdout_lines[3] }}"
    when: BlockchainInfo.stdout_lines[3][5:-2] != "dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C"
    ignore_errors: true

  - name: Check producer 3-3
    fail:
      msg: "Expected 'dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm' but returned {{ BlockchainInfo.stdout_lines[4] }}"
    when: BlockchainInfo.stdout_lines[4][5:-2] != "dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm"
    ignore_errors: true

  - name: Check producer 3-4
    fail:
      msg: "Expected 'dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3' but returned {{ BlockchainInfo.stdout_lines[5] }}"
    when: BlockchainInfo.stdout_lines[5][5:-2] != "dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3"
    ignore_errors: true

  - name: Check producer 3-5
    fail:
      msg: "Expected 'dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh' but returned {{ BlockchainInfo.stdout_lines[6] }}"
    when: BlockchainInfo.stdout_lines[6][5:-1] != "dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh"
    ignore_errors: true

  - name: Check producer 3-6
    fail:
      msg: "Expected ']' but returned {{ BlockchainInfo.stdout_lines[7] }}"
    when: BlockchainInfo.stdout_lines[7][-2:-1] != "]"
    ignore_errors: true