---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"

  tasks:
#################### Send Accounts.dat ####################
  - name: Make build
    make:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
      target: build
      file: /home/ubuntu/go/src/github.com/dappley/go-dappley/Makefile


#################### Create node6.conf ####################
  - name: Create node6.conf
    shell: '> node6.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf

  - name: Update node6.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node6.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'consensus_config{'
    - '    miner_address: "dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh"'
    - '    private_key: "555afabcf1f21a1516e3484f5884e627a74c1a9a6b1c6f13f05ceb3cf7d8c0d3"'
    - '    private_key: "555afabcf1f21a1516e3484f5884e627a74c1a9a6b1c6f13f05ceb3cf7d8c0d3"'
    - '}'
    - ' '
    - 'node_config{'
    - '    port:   12346'
    - '    seed:   ["/ip4/127.0.0.1/tcp/12341/p2p/QmNzA9rsEcM5nAzX9PzTrabJsGiifzaUU85Qe78HSDzSSE"]'
    - '    db_path: "../bin/node6.db"'
    - '    rpc_port: 50056'
    - '    key: "CAISICON1ta+r2QDKt2yC84JV0TWZFD7m8np65oCaN/m72Bw"'
    - '    tx_pool_limit: 102400'
    - '    blk_size_limit: 102400'
    - '    node_address: "dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh"'
    - '    metrics_interval: 7200'
    - '    metrics_polling_interval: 5'
    - '}'

  - name: Update node2 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50051'
      replace: 'port: 50052'
    when: inventory_hostname in groups['NODE2']

  - name: Update node3 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50051'
      replace: 'port: 50053'
    when: inventory_hostname in groups['NODE3']

  - name: Update node4 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50051'
      replace: 'port: 50054'
    when: inventory_hostname in groups['NODE4']

  - name: Update node5 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50051'
      replace: 'port: 50055'
    when: inventory_hostname in groups['NODE5']

  - name: Update node6 cli port
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      regexp: 'port: 50051'
      replace: 'port: 50056'
    when: inventory_hostname in groups['NODE6']


#################### Update seed on All nodes ####################
  - name: Update node1 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node1.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE2
    when: inventory_hostname in groups['NODE1']

  - name: Update node2 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node2.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE2']

  - name: Update node3 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node3.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE3']

  - name: Update node4 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node4.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE4']

  - name: Update node5 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node5.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE5']

  - name: Update node6 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node6.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE6']


#################### update genesis.conf ####################
  - name: Remove genesis.conf
    shell: 'rm -r genesis.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf

  - name: Create genesis.conf
    shell: '> genesis.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf

  - name: Update genesis.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/genesis.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'producers: ['
    - '"dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa",'
    - '"dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12",'
    - '"dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C",'
    - '"dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm",'
    - '"dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3",'
    - '"dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh"'
    - ']'
    - 'max_producers: 6'