---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"

  roles:
#################### Roles ####################
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/make_build
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/initialize_async
      node_number: 5
      async_runtime: 80
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/blockchain_status_check
      node_number: 5

  tasks:
#################### listAddresses when there is no accounts.dat ####################
  - name: List address without an accounts.dat
    ansible.builtin.expect:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
      command: ./cli listAddresses
      responses:
        'Please input the password:' : ''
    register: list_address
    ignore_errors: true

  - name: Test
    fail:
      msg: "Expected to fail but returned {{ list_address.stdout }}"
    when: list_address.stdout != "Please use cli createAccount to generate a account first!"
    ignore_errors: true

#################### listAddresses with private key when there is no accounts.dat ####################
  - name: List address and private key without an accounts.dat
    ansible.builtin.expect:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
      command: ./cli listAddresses -privateKey
      responses:
        'Please input the password:' : ''
    register: list_address
    ignore_errors: true

  - name: Test
    fail:
      msg: "Expected to fail but returned {{ list_address.stdout }}"
    when: list_address.stdout != "Please use cli createAccount to generate a account first!"
    ignore_errors: true

#################### List address with an incorrect password ####################
  - name: Create accounts.dat
    ansible.builtin.expect:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
      command: ./cli createAccount
      responses:
        'Please input the password for the new account:' : 'dappley'
        'Repeat password:' : 'dappley'
    register: test_result

  - name: Check if accounts.dat is working
    ansible.builtin.expect:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
      command: ./cli listAddresses
      responses:
        'Please input the password:' : 'dappley'
    register: list_address

  - name: Test
    fail:
      msg: 'Expected the accounts.dat to work but returned {{ list_address.stdout }}'
    when: list_address.stdout_lines[3][12:] != test_result.stdout_lines[4][35:69]
    ignore_errors: true

  - name: List address with incorrect poassword
    ansible.builtin.expect:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
      command: ./cli listAddresses
      responses:
        'Please input the password:' : 'wrong_password!'
    register: list_address

  - name: Test
    fail:
      msg: Expected the program to warn incorrect password, but returned {{ list_address.stdout }}
    when: list_address.stdout_lines[2][7:] != "password is incorrect"
    ignore_errors: true

#################### Terminate ####################
- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"
  roles:
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/terminate_async