---

- hosts: all
  become: true

  tasks:
#################### Update Cli Ports ####################
  - name: Remove default.conf
    shell: 'rm -r default.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli

  - name: Create default.conf
    shell: '> default.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50051'
    - 'password: "password"'
    when: inventory_hostname in groups['NODE1']

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50052'
    - 'password: "password"'
    when: inventory_hostname in groups['NODE2']

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50053'
    - 'password: "password"'
    when: inventory_hostname in groups['NODE3']

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50054'
    - 'password: "password"'
    when: inventory_hostname in groups['NODE4']

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50055'
    - 'password: "password"'
    when: inventory_hostname in groups['NODE5']

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50056'
    - 'password: "password"'
    when: 
      - "'NODE6' in groups"
      - inventory_hostname in groups['NODE6']

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50057'
    - 'password: "password"'
    when: 
      - "'NODE7' in groups"
      - inventory_hostname in groups['NODE7']

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50058'
    - 'password: "password"'
    when: 
      - "'NODE8' in groups"
      - inventory_hostname in groups['NODE8']

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50059'
    - 'password: "password"'
    when: 
      - "'NODE9' in groups"
      - inventory_hostname in groups['NODE9']

  - name: Update default.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli/default.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'port: 50050'
    - 'password: "password"'
    when: 
      - "'NODE10' in groups"
      - inventory_hostname in groups['NODE10']


#################### Update seed on All nodes ####################

########## Update node1 ##########
  - name: Update node1 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node1.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE2
    when: inventory_hostname in groups['NODE1']

########## Update node2 ##########
  - name: Update node2 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node2.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE2']

########## Update node3 ##########
  - name: Update node3 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node3.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: inventory_hostname in groups['NODE3']

########## Update node4 ##########
  - name: Update node4 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node4.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: 
      - "'NODE10' not in groups"
      - inventory_hostname in groups['NODE4']

  - name: Update node4 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node4.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE5
    when: 
      - "'NODE10' in groups"
      - inventory_hostname in groups['NODE4']

########## Update node5 ##########
  - name: Update node5 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node5.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: 
      - "'NODE10' not in groups"
      - inventory_hostname in groups['NODE5']

  - name: Update node5 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node5.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE4
    when: 
      - "'NODE10' in groups"
      - inventory_hostname in groups['NODE5']

########## Update node6 ##########
  - name: Update node6 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node6.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: 
      - "'NODE6' in groups"
      - inventory_hostname in groups['NODE6']

########## Update node7 ##########
  - name: Update node7 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node7.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: 
      - "'NODE7' in groups"
      - inventory_hostname in groups['NODE7']

########## Update node8 ##########
  - name: Update node8 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node8.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE1
    when: 
      - "'NODE8' in groups"
      - inventory_hostname in groups['NODE8']

  - name: Update node8 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node8.conf
      regexp: '127.0.1.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE5
    when: 
      - "'NODE8' in groups"
      - inventory_hostname in groups['NODE8']

########## Update node9 ##########
  - name: Update node9 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node9.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE5
    when: 
      - "'NODE9' in groups"
      - inventory_hostname in groups['NODE9']

########## Update node10 ##########
  - name: Update node10 seed
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node10.conf
      regexp: '127.0.0.1'
      replace: '{{ item }}'
    with_inventory_hostnames:
      - NODE5
    when: 
      - "'NODE10' in groups"
      - inventory_hostname in groups['NODE10']


#################### Update genesis.conf ####################
  - name: Remove genesis.conf
    shell: 'rm -r genesis.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf

  - name: Create genesis.conf
    shell: '> genesis.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf

  - name: Update genesis.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/genesis.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'producers: ['
    - '"dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa",'
    - '"dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12",'
    - '"dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C",'
    - '"dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm",'
    - '"dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3"'
    - ']'
    - 'max_producers: 5'
    when: 
    - "'NODE10' not in groups"

  - name: Update genesis.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/genesis.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'producers: ['
    - '"dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa",'
    - '"dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12",'
    - '"dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C",'
    - '"dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm",'
    - '"dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3",'
    - '"dNY1BMqsJVMRDp16ohsBACerdw5JQ931Eh",'
    - '"dc4d34HPJ8uyWE48K2huR2EL2LXYq8Snmd",'
    - '"da163VeoFUvvzor4sCxXJxTb4exjRRf1vB",'
    - '"dLwF9aPY1PtcHP7wqvY79uVgvaJHYm25AH",'
    - '"dGwRAfBEufqP5Wc3MkGGTC2XkrZkeEg61Z"'
    - ']'
    - 'max_producers: 10'
    when: 
    - "'NODE10' in groups"