---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"

  tasks:
#################### Make build ####################
  - name: Make build
    make:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley
      target: build
      file: /home/ubuntu/go/src/github.com/dappley/go-dappley/Makefile


#################### Update configuration files ####################

########## Update Node4 ##########
  - name: Update node4.conf
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node4.conf
      regexp: '"/ip4/127.0.0.1/tcp/12341/p2p/QmNzA9rsEcM5nAzX9PzTrabJsGiifzaUU85Qe78HSDzSSE"'
      replace: '{{ item }}'
    with_items:
    - '"/ip4/127.0.0.1/tcp/12345/p2p/16Uiu2HAmVer1v2PuXaJxbtCrhZb42CwNpg7MMcsWWVfyCmMiXhAr"'
    when: 
      - "'NODE10' in groups"
      - inventory_hostname in groups['NODE4']

########## Update Node5 ##########
  - name: Update node5.conf
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node5.conf
      regexp: '"/ip4/127.0.0.1/tcp/12341/p2p/QmNzA9rsEcM5nAzX9PzTrabJsGiifzaUU85Qe78HSDzSSE"'
      replace: '{{ item }}'
    with_items:
    - '"/ip4/127.0.0.1/tcp/12344/p2p/16Uiu2HAmF1xtzd6XGr9WcPD9vAt32igx2Y7UnBR9JG6HbG5UNc6T"'
    when: 
      - "'NODE10' in groups"
      - inventory_hostname in groups['NODE5']

########## Update Node8 ##########
  - name: Update node8.conf
    ansible.builtin.replace:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/node8.conf
      regexp: '"/ip4/127.0.0.1/tcp/12341/p2p/QmNzA9rsEcM5nAzX9PzTrabJsGiifzaUU85Qe78HSDzSSE"'
      replace: '{{ item }}'
    with_items:
    - '\n                "/ip4/127.0.0.1/tcp/12341/p2p/QmNzA9rsEcM5nAzX9PzTrabJsGiifzaUU85Qe78HSDzSSE",\n                "/ip4/127.0.1.1/tcp/12345/p2p/16Uiu2HAmVer1v2PuXaJxbtCrhZb42CwNpg7MMcsWWVfyCmMiXhAr"\n            '
    when: 
      - "'NODE8' in groups"
      - inventory_hostname in groups['NODE8']