  - name: Copy accounts.dat to NODE1
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node1/accounts.dat
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/bin/
    when: node_number.find("1") and inventory_hostname in groups['NODE1']

  - name: Copy accounts.dat to NODE2
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node2/accounts.dat
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/bin/
    when: node_number.find("2") and inventory_hostname in groups['NODE2']

  - name: Copy accounts.dat to NODE3
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node3/accounts.dat
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/bin/
    when: node_number.find("3") and inventory_hostname in groups['NODE3']

  - name: Copy accounts.dat to NODE4
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node4/accounts.dat
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/bin/
    when: node_number.find("4") and inventory_hostname in groups['NODE4']

  - name: Copy accounts.dat to NODE5
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node5/accounts.dat
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/bin/
    when: node_number.find("5") and inventory_hostname in groups['NODE5']