---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"

  pre_tasks:
#################### Update genesis.conf ####################
  - name: Remove genesis.conf
    shell: 'sudo rm -r genesis.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf

  - name: Create genesis.conf
    shell: '> genesis.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf

  - name: Update genesis.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/genesis.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'producers: ['
    - '"dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa",'
    - '"dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12",'
    - '"dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C",'
    - '"dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm"'
    - ']'
    - 'max_producers: 4'

  roles:
#################### Roles ####################
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/make_build
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/initialize_async
      node_number: 5
      async_runtime: 220
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/blockchain_status_check
      node_number: 5

  tasks:
#################### Launch new node ####################
  - name: Launch NODE6
    shell: ./dapp -f conf/node6.conf
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp
    when: inventory_hostname in groups['NODE6']
    async: 170
    poll: 0

#################### Check if the blockchain height is increasing ####################
  - name: Get BlockchainInfo
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight
    when: inventory_hostname in groups['NODE6']

  - name: Check if height increaments
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight_new
    until: (blockchainHeight_new.stdout_lines[1][17:-1])|int > (blockchainHeight.stdout_lines[1][17:-1])|int
    retries: 20
    delay: 10
    ignore_errors: true
    when: inventory_hostname in groups['NODE6']

  - name: Wait a minute
    wait_for:
      timeout: 60

#################### Compare blockchain height ####################
  - name: Get BlockchainInfo
    shell: ./cli getBlockchainInfo
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/cli
    register: blockchainHeight

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/height
      state: directory
      mode: '0755'

########## NODE 1 ##########
  - name: Create height info file
    shell: '> height_1.txt'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']

  - debug:
      msg: '{{ blockchainHeight }}'

  - debug:
      msg: '{{ blockchainHeight.stdout_lines[1][17:-1] }}'

  - name: Write height info to file
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/height_1.txt
      state: present
      line: '{{ blockchainHeight.stdout_lines[1][17:-1] }}'
    when: inventory_hostname in groups['NODE1']

########## NODE 2 ##########
  - name: Create height info file
    shell: '> height_2.txt'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/
    when: inventory_hostname in groups['NODE2']

  - name: Write height info to file
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_2.txt
      state: present
      line: '{{ blockchainHeight.stdout_lines[1][17:-1] }}'
    when: inventory_hostname in groups['NODE2']

########## NODE 3 ##########
  - name: Create height info file
    shell: '> height_3.txt'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/
    when: inventory_hostname in groups['NODE3']

  - name: Write height info to file
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_3.txt
      state: present
      line: '{{ blockchainHeight.stdout_lines[1][17:-1] }}'
    when: inventory_hostname in groups['NODE3']

########## NODE 4 ##########
  - name: Create height info file
    shell: '> height_4.txt'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/
    when: inventory_hostname in groups['NODE4']

  - name: Write height info to file
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_4.txt
      state: present
      line: '{{ blockchainHeight.stdout_lines[1][17:-1] }}'
    when: inventory_hostname in groups['NODE4']

########## NODE 5 ##########
  - name: Create height info file
    shell: '> height_5.txt'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/
    when: inventory_hostname in groups['NODE5']

  - name: Write height info to file
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_5.txt
      state: present
      line: '{{ blockchainHeight.stdout_lines[1][17:-1] }}'
    when: inventory_hostname in groups['NODE5']

########## NODE 6 ##########
  - name: Create height info file
    shell: '> height_6.txt'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/
    when: inventory_hostname in groups['NODE6']

  - name: Write height info to file
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_6.txt
      state: present
      line: '{{ blockchainHeight.stdout_lines[1][17:-1] }}'
    when: inventory_hostname in groups['NODE6']

#################### Move files to NODE1 ####################
  - name: Move height info to Jenkins
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_2.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node2/
      flat: yes
    when: inventory_hostname in groups['NODE2']

  - name: Move height info to Jenkins
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_3.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node3/
      flat: yes
    when: inventory_hostname in groups['NODE3']

  - name: Move height info to Jenkins
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_4.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node4/
      flat: yes
    when: inventory_hostname in groups['NODE4']

  - name: Move height info to Jenkins
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_5.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node5/
      flat: yes
    when: inventory_hostname in groups['NODE5']

  - name: Move height info to Jenkins
    fetch:
      src: /home/ubuntu/go/src/github.com/dappley/go-dappley/height_6.txt
      dest: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node6/
      flat: yes
    when: inventory_hostname in groups['NODE6']

  - name: Move height info to NODE1
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node2/height_2.txt
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']

  - name: Move height info to NODE1
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node3/height_3.txt
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']

  - name: Move height info to NODE1
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node4/height_4.txt
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']

  - name: Move height info to NODE1
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node5/height_5.txt
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']

  - name: Move height info to NODE1
    copy:
      src: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/accounts/node6/height_6.txt
      dest: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']

#################### Compare heights ####################
  - name: Check height_1
    shell: cat height_1.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']
    register: height_1

  - name: Check height_2
    shell: cat height_2.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']
    register: height_2

  - name: Check height_3
    shell: cat height_3.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']
    register: height_3

  - name: Check height_4
    shell: cat height_4.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']
    register: height_4

  - name: Check height_5
    shell: cat height_5.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']
    register: height_5

  - name: Check height_6
    shell: cat height_6.txt
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/height/
    when: inventory_hostname in groups['NODE1']
    register: height_6

  - name: Check all nodes height
    fail:
      msg: "Expected the block height of all nodes to be the same, but returned different values!"
    ignore_errors: true
    when: inventory_hostname in groups['NODE1'] and not (height_1.stdout|int == height_2.stdout|int == height_3.stdout|int == height_4.stdout|int == height_5.stdout|int == height_6.stdout|int)

#################### Terminate ####################
- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"
  roles:
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/terminate_async

  tasks:
#################### Update genesis.conf ####################
  - name: Remove genesis.conf
    shell: 'rm -r genesis.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf

  - name: Create genesis.conf
    shell: '> genesis.conf'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf

  - name: Update genesis.conf
    lineinfile:
      path: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/conf/genesis.conf
      state: present
      line: "{{ item }}"
    with_items:
    - 'producers: ['
    - '"dastXXWLe5pxbRYFhcyUq8T3wb5srWkHKa",'
    - '"dUuPPYshbBgkzUrgScEHWvdGbSxC8z4R12",'
    - '"dPGD4t6ibpmyKZnXH1TNbbPw98EDaaZq8C",'
    - '"dUa6gQkijmVqf7pk9cmRS6M9nMnU6b9Ssm",'
    - '"dTSNWQeFNRJBEQEhuDJNdu219r389CSkh3"'
    - ']'
    - 'max_producers: 5'