---

- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"
  vars:
    peerID1: peer_ID_1
    peerID2: peer_ID_2
    peerID3: peer_ID_3
    peerID4: peer_ID_4
    peerID5: peer_ID_5

  roles:
#################### make_build, initialize_async & blockchain_status_check ####################
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/make_build
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/initialize_async
      node_number: 5
      async_runtime: 60
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/blockchain_status_check
      node_number: 5

  tasks:
#################### Check PeerID node1 ####################
  - name: Check PeerID Node1
    shell: grep -rnw '.' -e '{{ peerID1 }}'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/log
    when: inventory_hostname in groups['NODE1']
    register: peerID_check_node1

  - name: Test node1 PeerID
    fail:
      msg: Expected to find the peerID {{ peerID1 }} in the log file, but peer ID is not found!"
    when: inventory_hostname in groups['NODE1'] and peerID_check_node1.stdout == ""
    ignore_errors: true

#################### Check PeerID node2 ####################
  - name: Check PeerID Node2
    shell: grep -rnw '.' -e '{{ peerID2 }}'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/log
    when: inventory_hostname in groups['NODE2']
    register: peerID_check_node2

  - name: Test node2 PeerID
    fail:
      msg: Expected to find the peerID {{ peerID2 }} in the log file, but peer ID is not found!"
    when: inventory_hostname in groups['NODE2'] and peerID_check_node2.stdout == ""
    ignore_errors: true

#################### Check PeerID node3 ####################
  - name: Check PeerID Node3
    shell: grep -rnw '.' -e '{{ peerID3 }}'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/log
    when: inventory_hostname in groups['NODE3']
    register: peerID_check_node3

  - name: Test node3 PeerID
    fail:
      msg: Expected to find the peerID {{ peerID3 }} in the log file, but peer ID is not found!"
    when: inventory_hostname in groups['NODE3'] and peerID_check_node3.stdout == ""
    ignore_errors: true

#################### Check PeerID node4 ####################
  - name: Check PeerID Node4
    shell: grep -rnw '.' -e '{{ peerID4 }}'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/log
    when: inventory_hostname in groups['NODE4']
    register: peerID_check_node4

  - name: Test node4 PeerID
    fail:
      msg: Expected to find the peerID {{ peerID4 }} in the log file, but peer ID is not found!"
    when: inventory_hostname in groups['NODE4'] and peerID_check_node4.stdout == ""
    ignore_errors: true

#################### Check PeerID node5 ####################
  - name: Check PeerID Node5
    shell: grep -rnw '.' -e '{{ peerID5 }}'
    args:
      chdir: /home/ubuntu/go/src/github.com/dappley/go-dappley/dapp/log
    when: inventory_hostname in groups['NODE5']
    register: peerID_check_node5

  - name: Test node5 PeerID
    fail:
      msg: Expected to find the peerID {{ peerID5 }} in the log file, but peer ID is not found!"
    when: inventory_hostname in groups['NODE5'] and peerID_check_node5.stdout == ""
    ignore_errors: true

#################### Terminate ####################
- hosts: all
  become: true
  become_user: ubuntu
  environment:
    GOPATH: "/home/ubuntu/go"
    GOROOT: "/usr/local/go"
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/ubuntu/go/bin"
  roles:
    - role: /var/lib/jenkins/workspace/go-dappley-multi-server-tester/roles/terminate_async